name: mute_zones
description: "A location-based mute app that automatically silences your phone when you enter predefined zones."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.3
  geolocator: ^10.1.0
  shared_preferences: ^2.2.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
